choria-io/appbuilder

README.md
=> (misc) add quickstart demo

builder/builder.go, builder/templates.go
=> (misc) fix a few bugs found while making wiki docs

.goreleaser.yaml, NOTICE, README.md
=> (#14) publish homebrew packages

.goreleaser.yaml, builder/builder.go
=> (#17) fix config locations selection

commands/exec/exec.go, commands/parent/parent.go
=> (#19) support environment variables for exec

.goreleaser.yaml
=> (#14) fix path to archives

builder/generic.go
=> (#23) Support enums on arguments and flags

builder/generic.go
=> (#25) support flag and argument defaults

.github/workflows/docs.yml, go.mod, go.sum
=> (misc) attempt to fix docs publish

docs/config.toml
=> fix base url for docs

README.md
=> (misc) mention the new docs

docs/config.toml
=> (misc) add download link

docs/config.toml, docs/content/_index.md, docs/content/reference/_index.md
=> (misc) try to improve mobile experience

builder/cli.go
=> (#36) improve handling of user supplied loggers

builder/builder.go
=> (#39) allow it to be embedded in other commands

builder/builder.go, docs/content/reference/running-validation.md
=> (#39) less noise about commit hashes etc

builder/generic.go, builder/generic_test.go, commands/exec/exec.go
=> (#44) adds support for emitting a warning banner

commands/exec/exec.go, commands/parent/parent.go
=> (misc) add non fatal registration helpers

builder/builder.go, builder/cli.go, builder/generic.go, builder/generic_test.go, commands/exec/exec.go, commands/exec/exec_test.go, commands/parent/parent.go, commands/parent/parent_test.go, docs/content/_index.md, docs/content/reference/templating.md, go.mod, go.sum
=> (#51) use kingpin master and a custom usage template

docs/content/quick-start/_index.md, docs/content/reference/_index.md, docs/content/reference/configuration.md, docs/content/reference/exec.md, docs/content/reference/kv.md, docs/content/reference/running-validation.md, docs/content/reference/templating.md
=> (misc) Add documentation for the kv command

docs/content/reference/rpc.md
=> (misc) document the rpc type

docs/content/reference/rpc.md
=> (misc) syntax fix in docs

docs/content/quick-start/_index.md, docs/content/reference/file-locations.md
=> (docs) Update docs to include file locations on a Mac

commands/exec/exec.go, commands/exec/exec_test.go, docs/content/reference/common-settings.md, docs/content/reference/exec.md
=> (#64) add a shell script feature for exec

go.mod, go.sum
=> (misc) Release v0.0.8

builder/builder.go, builder/definition.go, builder/definition_test.go, docs/content/reference/common-settings.md
=> (#69) support help template selection

builder/builder.go, builder/generic.go, builder/generic_test.go, builder/templates.go, commands/exec/exec.go, commands/parent/parent.go, main.go
Booleans are supported with automatic handling
of negatable bools when the default is set to
true.
=> (#16) support boolean flags

builder/generic.go, docs/content/reference/common-settings.md
=> (#12) allow confirm_prompt to be disabled using --no-prompt

.gitignore, README.md, builder/builder.go, builder/generic.go, builder/generic_test.go, builder/logger.go, builder/options.go, commands/exec/exec.go, docs/content/reference/common-settings.md, example/example_test.go, example/sample-app.yaml
This improves flags and transformations:
* Flags can have environment overrides
* Flags can have short versions
* JQ queries are templated
* Documentation for flags and args were improved
* An example application with almost all features showcased added
* The example application is used as an integration test
=> (#88,#87,#83) flag improvements

builder/generic.go, builder/generic_test.go, builder/transform.go, builder/transform_bar_graph.go, builder/transform_jq.go, builder/transform_line_graph.go, builder/transform_pipeline.go, commands/exec/exec.go, docs/content/reference/cheats.md, docs/content/reference/configuration.md, docs/content/reference/exec.md, docs/content/reference/file-locations.md, docs/content/reference/kv.md, docs/content/reference/parent.md, docs/content/reference/rpc.md, docs/content/reference/running-validation.md, docs/content/reference/templating.md, docs/content/reference/transformations.md, example/sample-app.yaml, go.mod, go.sum
This adds support for multiple transforms
and uses that to make a pipeline of transforms
Adds line_graph and bar_graph transforms
=> wip pipelines

builder/builder.go, docs/content/reference/common-settings.md, go.mod, go.sum
=> (#91) adds a columns help template

builder/builder.go, builder/definition.go, builder/definition_test.go
=> (#91) fix validation for columns help template

builder/builder.go, builder/definition.go, builder/definition_test.go, docs/content/reference/common-settings.md
=> (#91) move default help template to CompactMainUsageTemplate

builder/generic.go
=> (#97) show banner before prompting

README.md, builder/transform_jq.go, example/example_test.go, example/sample-app.yaml
This should now also accept arrays into jq
Also update video link and rework sampla app
=> (#96) accept all json in jq transforms

docs/config.toml, docs/layouts/partials/custom-header.html
=> (misc) add google analytics

builder/transform.go, builder/trasnform_write_file.go, docs/content/reference/transformations.md, example/sample-app.yaml
=> (#107) add a file write transform

docs/content/reference/exec.md
=> (#110) minor doc updates

builder/builder.go, builder/generic.go, builder/logger.go, commands/exec/exec.go, commands/scaffold/scaffold.go, docs/content/reference/scaffold.md, scaffold/scaffold.go
* Additional template functions available to source/target
* A way to skip empty files
* A way to customize delimiters
* Improved logging
* More template functions available to the generic banner
=> (#141) Various scaffold improvements

builder/builder.go, builder/definition.go, commands/parent/parent.go, docs/content/experiments/_index.md, docs/content/reference/common-settings.md, example/example_test.go, example/go.yaml, example/include-app.yaml, example/sample-app.yaml, go.mod, go.sum
=> (#170) Support including definitions
